version: '2'
services:
    nginx:
        image: nginx:1.13.5
        ports:
            - 80:80/tcp
        networks:
            h5ai:
                aliases:
                    - nginx
        volumes:
            - ./www:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
    php:
        image: php:5.6.31-fpm-alpine3.4
        networks:
            h5ai:
                aliases:
                    - php
        volumes:
            - ./www:/var/www/html
networks:
    h5ai:
