version: '2'
services:
    registry:
        image: registry:2.6.1
        hostname: registry
        ports:
            - 443:5000/tcp
        networks:
            registry:
                aliases:
                    - registry
        volumes:
            - /var/lib/registry:/var/lib/registry:rw
            - /home/certs:/certs
        environment:
            - REGISTRY_AUTH=token
            - REGISTRY_AUTH_TOKEN_REALM=https://registry.example.com:5001/auth
            - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
            - REGISTRY_AUTH_TOKEN_ISSUER="Auth Service"
networks:
    registry:
        external: true
