version: '2'
services:
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306/tcp
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=pureftpd
            - MYSQL_USER=pureftpd
            - MYSQL_PASSWORD=pureftpd
        networks:
            ftp:
                aliases:
                    - mysql
    ftp:
        image: semprunl/pure-ftpd-mysql
        environment:
            - MYSQL_SERVER=mysql
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=pureftpd
networks:
    ftp:
        external: true
