version: '3.4'
services:
    gitlab:
        image: twang2218/gitlab-ce-zh:10.5.4
        hostname: gitlab.xmitd.com
        ports:
            - 3001:80
            - 3002:443
            - 3003:22
        environment:
            TZ: 'Asia/Shanghai'
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://10.0.0.135'
                gitlab_rails['time_zone'] = 'Asia/Shanghai'
                gitlab_rails['smtp_enable'] = false
        volumes:
            - /mnt/nfs/gitlab/etc:/etc/gitlab
            - /mnt/nfs/gitlab/opt:/var/opt/gitlab
            - /mnt/nfs/gitlab/log:/var/log/gitlab
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.gitlab == true
        networks:
            gitlab:
                aliases:
                    - gitlab
networks:
    gitlab:
        external: true