version: '3.4'
services:
    gitlab:
        image: 'twang2218/gitlab-ce-zh:9.3.4'
        hostname: 'gitlab.xmitd.com'
        environment:
            TZ: 'Asia/Shanghai'
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://gitlab.xmitd.com'
                gitlab_rails['time_zone'] = 'Asia/Shanghai'
                gitlab_rails['smtp_enable'] = false
        volumes:
            - /gitlab/config:/etc/gitlab
            - /gitlab/data:/var/opt/gitlab
            - /gitlab/logs:/var/log/gitlab
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == gitlab
        networks:
            gitlab:
                aliases:
                    - gitlab
networks:
    gitlab:
        external: true
