version: '3'
services:
    nginx:
        image: daocloud.io/buxiaomo/nginx:1.13.8-alpine
        ports:
            - 80:80/tcp
        networks:
            h5ai:
                aliases:
                    - nginx
        environment:
            - GIT_URL=https://github.com/buxiaomo/configfile.git
            - Configure_File_SCR_1=h5ai/nginx.conf
            - Configure_File_DEST_1=/etc/nginx/nginx.conf
        volumes:
            - ./www:/var/www/html
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: global
            placement:
                constraints: [node.role == manager]
    h5ai:
        image: daocloud.io/buxiaomo/h5ai:0.29.0
        networks:
            h5ai:
                aliases:
                    - h5ai
        volumes:
            - ./www:/var/www/html
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: global
            placement:
                constraints: [node.role == manager]
networks:
    h5ai:
