version: '3'
services:
    jetbrains:
        image: daocloud.io/buxiaomo/intellijidealicenseserver:latest
        hostname: jetbrains
        ports:
            - 1017:1017/tcp
        networks:
            jetbrains:
                aliases:
                    - jetbrains
        healthcheck:
            test: ["CMD", "nc", "-w", "1", "localhost", "1017", "-z"]
            interval: 10s
            timeout: 5s
            retries: 3
        deploy:
            mode: global
networks:
    jetbrains:
        external: true
