version: '3.4'
services:
    openldap:
        image: dinkel/openldap
        hostname: openldap
        ports:
            - "389:389"
        environment:
            - SLAPD_PASSWORD=password
            - SLAPD_DOMAIN=daocloud.io
        networks:
            openldap:
                aliases:
                    - openldap
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
    phpldapadmin:
        image: dinkel/phpldapadmin
        hostname: phpldapadmin
        ports:
            - "8080:80"
        networks:
            openldap:
                aliases:
                    - phpldapadmin
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
networks:
    openldap:
        external: true
