version: '3.4'
services:
    management1:
        image: mysql/mysql-cluster:7.5
        hostname: management1
        command: ndb_mgmd
        networks:
            cluster:
                aliases:
                    - management1
                ipv4_address: 192.168.0.2
        volumes:
            - /opt/splunk/var:/opt/splunk/var:rw
            - /opt/splunk/etc:/opt/splunk/etc:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
    ndb1:
        image: mysql/mysql-cluster:7.5
        hostname: ndb1
        command: ndbd
        networks:
            cluster:
                aliases:
                    - ndb1
                ipv4_address: 192.168.0.3
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
    ndb2:
        image: mysql/mysql-cluster:7.5
        hostname: ndb2
        command: ndbd
        networks:
            cluster:
                aliases:
                    - ndb2
                ipv4_address: 192.168.0.4
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
    mysql1:
        image: mysql/mysql-cluster:7.5
        hostname: ndb2
        command: mysqld
        networks:
            cluster:
                aliases:
                    - ndb2
                ipv4_address: 192.168.0.10
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=true
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
networks:
    cluster:
        external: true
        driver_opts:
            com.docker.network.enable_ipv6: "false"
