version: '2'
services:
    registry:
        image: registry:2.6.1
        hostname: registry
        ports:
            - 80:5000/tcp
        networks:
            registry:
                aliases:
                    - registry
        environment:
            - REGISTRY_STORAGE=oss
            - REGISTRY_STORAGE_OSS_ACCESSKEYID=<accesskey_id>
            - REGISTRY_STORAGE_OSS_ACCESSKEYSECRET=<accesskey_secret>
            - REGISTRY_STORAGE_OSS_REGION=<region_id>
            - REGISTRY_STORAGE_OSS_BUCKET=<bucket_name>
            - REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=redis
            - REGISTRY_REDIS_ADDR=redis:6379
    redis:
        image: redis:4.0.6
        hostname: redis
        networks:
            registry:
                aliases:
                    - redis
        volumes:
            - /redis/registry:/data:rw
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == Docker-Swarm-Redis
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
networks:
    registry:
        external: true

# Registry主机
# openssl req -newkey rsa:4096 -nodes -sha256 -keyout hub.xmitd.com.key -x509 -days 365 -out hub.xmitd.com.crt
# Client主机
# mkdir -p /etc/docker/certs.d/hub.xmitd.com
# /home/certs/hub.xmitd.com.crt是registry主机生成的
# cp /home/certs/hub.xmitd.com.crt /etc/docker/certs.d/hub.xmitd.com/
