version: '2'
services:
    registry:
        image: registry:2.6.1
        hostname: registry
        ports:
            - 443:5000/tcp
        networks:
            registry:
                aliases:
                    - registry
        volumes:
            - /home/certs:/certs
        environment:
            - REGISTRY_HTTP_TLS_KEY=/certs/gcr.io.key
            - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/gcr.io.crt

# openssl req -newkey rsa:4096 -nodes -sha256 -keyout gcr.io.key -x509 -days 365 -out gcr.io.crt
