version: '3.4'
services:
    server:
        image: splunk/splunk:7.0.0
        hostname: splunkserver
        environment:
            - SPLUNK_ENABLE_DEPLOY_SERVER=true
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_ENABLE_LISTEN=9997
            - SPLUNK_CMD_1=edit cluster-config -mode master -replication_factor 2 -search_factor 2 -secret admin -cluster_label swarm -auth admin:changeme
            - SPLUNK_CMD_2=restart
        ports:
            - 8000:8000/tcp
            - 8088:8088/tcp
        networks:
            splunk:
                aliases:
                    - splunkserver
        volumes:
            - /opt/splunk/var:/opt/splunk/var:rw
            - /opt/splunk/etc:/opt/splunk/etc:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.hostname == Docker-Swarm-Splunk
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
    indexer01:
        image: splunk/splunk:7.0.0
        hostname: indexer01
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_ENABLE_LISTEN=9997
            - SPLUNK_CMD_1=disable webserver -auth admin:changeme
            - SPLUNK_CMD_2=edit cluster-config -mode slave -master_uri https://splunkserver:8089 -replication_port 9887 -secret admin -auth admin:changeme
            - SPLUNK_CMD_3=restart
        networks:
            splunk:
                aliases:
                    - indexer01
        depends_on:
            - splunkserver
        volumes:
            - /var/lib/docker/containers:/host/containers
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
            - /opt/splunk/var:/opt/splunk/var:rw
            - /opt/splunk/etc:/opt/splunk/etc:rw
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.hostname == Docker-Swarm-Indexer01
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
    indexer02:
        image: splunk/splunk:7.0.0
        hostname: indexer02
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_ENABLE_LISTEN=9997
            - SPLUNK_CMD_1=disable webserver -auth admin:changeme
            - SPLUNK_CMD_2=edit cluster-config -mode slave -master_uri https://splunkserver:8089 -replication_port 9887 -secret admin -auth admin:changeme
            - SPLUNK_CMD_3=restart
        networks:
            splunk:
                aliases:
                    - indexer02
        depends_on:
            - splunkserver
        volumes:
            - /var/lib/docker/containers:/host/containers
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
            - /opt/splunk/var:/opt/splunk/var:rw
            - /opt/splunk/etc:/opt/splunk/etc:rw
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.hostname == Docker-Swarm-Indexer02
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
networks:
    splunk:
        external: true
