version: '3'
services:
    splunk:
        hostname: splunk
        image: splunk/splunk:7.0.0
        environment:
            SPLUNK_START_ARGS: --accept-license
            SPLUNK_ENABLE_LISTEN: 9997
            SPLUNK_ADD: tcp 1514
        ports:
            - "8000:8000"
            - "9997:9997"
            - "8088:8088"
            - "1514:1514"
    indexer01:
        hostname: indexer01
        image: splunk/splunk:7.0.0
        environment:
            SPLUNK_START_ARGS: --accept-license
            SPLUNK_ENABLE_LISTEN: 9997
            SPLUNK_ADD: tcp 1514
    indexer02:
        hostname: indexer01
        image: splunk/splunk:7.0.0
        environment:
            SPLUNK_START_ARGS: --accept-license
            SPLUNK_ENABLE_LISTEN: 9997
            SPLUNK_ADD: tcp 1514
volumes:
    opt-splunk-etc:
    opt-splunk-var:
