version: '3.4'
services:
    server:
        image: daocloud.io/buxiaomo/splunk:7.0.0
        hostname: server
        environment:
            - SPLUNK_START_ARGS=--accept-license --answer-yes
            - SPLUNK_ENABLE_LISTEN=9997
            - SPLUNK_CMD_1=edit cluster-config -mode master -replication_factor 2 -search_factor 2 -secret admin -cluster_label swarm -auth admin:changeme
            - SPLUNK_CMD_2=set servername splunk-server -auth admin:changeme
            - SPLUNK_CMD_3=restart
        networks:
            splunk:
        volumes:
            - /opt/splunk/var:/opt/splunk/var:rw
            - /opt/splunk/etc:/opt/splunk/etc:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.hostname == splunk-server
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
    searchead01:
        image: daocloud.io/buxiaomo/splunk:7.0.0
        hostname: searchead01
        environment:
            - SPLUNK_START_ARGS=--accept-license --answer-yes
            - SPLUNK_CMD_1=set servername searchead01 -auth admin:changeme
            - SPLUNK_CMD_2=edit cluster-config -mode searchhead -master_uri https://10.3.236.31:8089 -secret admin
            - SPLUNK_CMD_3=restart
        networks:
            splunk:
        depends_on:
            - splunkserver
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
            - /opt/splunk/var:/opt/splunk/var:rw
            - /opt/splunk/etc:/opt/splunk/etc:rw
        deploy:
            mode: replicated
            replicas: 0
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.hostname == splunk-searchead01
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
    deployment:
        image: daocloud.io/buxiaomo/splunk:7.0.0
        hostname: deployment
        environment:
            - SPLUNK_START_ARGS=--accept-license --answer-yes
            - SPLUNK_ENABLE_DEPLOY_SERVER=true
            - SPLUNK_DEPLOYMENT_SERVER=10.3.236.31:8089
            - SPLUNK_CMD_1=set servername deployment -auth admin:changeme
            - SPLUNK_CMD_2=edit licenser-localslave -master_uri 'https://10.3.236.31:8089' -auth admin:changeme
            - SPLUNK_CMD_3=restart
        networks:
            splunk:
        depends_on:
            - splunkserver
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
            - /opt/splunk/var:/opt/splunk/var:rw
            - /opt/splunk/etc:/opt/splunk/etc:rw
        deploy:
            mode: replicated
            replicas: 0
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.hostname == splunk-department
    indexer01:
        image: daocloud.io/buxiaomo/splunk:7.0.0
        hostname: indexer01
        environment:
            - SPLUNK_START_ARGS=--accept-license --answer-yes
            - SPLUNK_ENABLE_LISTEN=9997
            - SPLUNK_DEPLOYMENT_SERVER=10.3.236.31:8089
            - SPLUNK_CMD_1=disable webserver -auth admin:changeme
            - SPLUNK_CMD_2=edit cluster-config -mode slave -master_uri https://10.3.236.31:8089 -replication_port 9887 -secret admin -auth admin:changeme
            - SPLUNK_CMD_3=set servername indexer01 -auth admin:changeme
            - SPLUNK_CMD_4=edit licenser-localslave -master_uri 'https://10.3.236.31:8089' -auth admin:changeme
            - SPLUNK_CMD_5=restart
        networks:
            splunk:
        depends_on:
            - splunkserver
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
            - /opt/splunk/var:/opt/splunk/var:rw
            - /opt/splunk/etc:/opt/splunk/etc:rw
        deploy:
            mode: replicated
            replicas: 0
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.hostname == splunk-indexer01
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
    indexer02:
        image: daocloud.io/buxiaomo/splunk:7.0.0
        hostname: indexer02
        environment:
            - SPLUNK_START_ARGS=--accept-license --answer-yes
            - SPLUNK_ENABLE_LISTEN=9997
            - SPLUNK_DEPLOYMENT_SERVER=10.3.236.31:8089
            - SPLUNK_CMD_1=disable webserver -auth admin:changeme
            - SPLUNK_CMD_2=edit cluster-config -mode slave -master_uri https://10.3.236.31:8089 -replication_port 9887 -secret admin -auth admin:changeme
            - SPLUNK_CMD_3=set servername indexer02 -auth admin:changeme
            - SPLUNK_CMD_4=edit licenser-localslave -master_uri 'https://10.3.236.31:8089'
            - SPLUNK_CMD_5=restart
        networks:
            splunk:
        depends_on:
            - splunkserver
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
            - /opt/splunk/var:/opt/splunk/var:rw
            - /opt/splunk/etc:/opt/splunk/etc:rw
        deploy:
            mode: replicated
            replicas: 0
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.hostname == splunk-indexer02
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
networks:
    splunk:
        external:
            name: "host"

# docker stack deploy -c splunk_cluster.yml splunk

# When splunk server initialization is complete run the following command to start index:
# docker service scale splunk_indexer01=1 splunk_indexer02=1 -d

# Run the following command to start universalforwarder after index initialization is completed
# docker service scale splunk_forward-monitor-docker=1 -d
