version: '3.4'
services:
    ftp:
        image: daocloud.io/buxiaomo/proftpd:1.3.5a
        ports:
            - 20:20/tcp
            - 21:21/tcp
            - 60000-60100:60000-60100/tcp
        networks:
            virtualhost:
                aliases:
                    - ftp
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - MYSQL_DATABASE=ftp
            - MYSQL_USER=ftp
            - MYSQL_PASSWORD=ftp
        volumes:
            - ./www:/var/www
            - /run/docker.sock:/run/docker.sock:ro
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                # order: start-first
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.labels.virtualhost.ftp == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
        # healthcheck:
        #     test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
        #     interval: 10s
        #     timeout: 5s
        #     retries: 3

    mysql:
        image: mysql:5.7.20
        ports:
            - 3306:3306/tcp
        networks:
            virtualhost:
                aliases:
                    - mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=ftp
            - MYSQL_USER=ftp
            - MYSQL_PASSWORD=ftp
        configs:
          - source: mysql
            target: /etc/mysql/mysql.conf.d/mysqld.cnf
        volumes:
            - ./mysql/data:/var/lib/mysql
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                # order: start-first
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.labels.virtualhost.mysql == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
        # healthcheck:
        #     test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
        #     interval: 10s
        #     timeout: 5s
        #     retries: 3

configs:
    mysql:
        file: ./mysql/mysqld.cnf

networks:
    virtualhost:
        external: true