version: '3.4'
services:
    nginx:
        image: nginx:1.13.8-alpine
        ports:
            - 10000:80/tcp
        networks:
            lnmp72:
                aliases:
                    - nginx
        configs:
          - source: nginx
            target: /etc/nginx/nginx.conf
        volumes:
            - ../www:/var/www/html:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '0.50'
                    memory: 100M
                reservations:
                    cpus: '0.25'
                    memory: 50M
            update_config:
                order: start-first
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.labels.lnmp == true
        # healthcheck:
        #     test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
        #     interval: 10s
        #     timeout: 5s
        #     retries: 3
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
        # logging:
        #     driver: syslog
        #     options:
        #         syslog-address: "tcp://10.211.55.61:514"
        #         tag: "nginx"

    php:
        image: php:7.2.5-fpm-alpine3.7
        networks:
            lnmp72:
                aliases:
                    - php
        configs:
          - source: php
            target: /usr/local/etc/php/php.ini
          - source: phpuploads
            target: /usr/local/etc/php/conf.d/uploads.ini
        volumes:
            - ../www:/var/www/html:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '0.50'
                    memory: 100M
                reservations:
                    cpus: '0.25'
                    memory: 50M
            update_config:
                order: start-first
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.labels.lnmp == true
        # healthcheck:
        #     test: ["CMD-SHELL", "curl -f http://localhost:9000/ || exit 1"]
        #     interval: 10s
        #     timeout: 5s
        #     retries: 3
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
        # logging:
        #     driver: syslog
        #     options:
        #         syslog-address: "tcp://10.211.55.61:514"
        #         tag: "php"

configs:
    nginx:
        file: ./nginx/nginx.conf
    php:
        file: ./php/php.ini
    phpuploads:
        file: ./php/ext/uploads.ini

networks:
    lnmp72:
        external: true